/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_weblite_webview_WebViewNative */

#ifndef _Included_ca_weblite_webview_WebViewNative
#define _Included_ca_weblite_webview_WebViewNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_create
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1create
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1destroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_run
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1run
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_terminate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1terminate
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_dispatch
 * Signature: (JLjava/lang/Runnable;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1dispatch
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_get_window
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_webview_WebViewNative_webview_1get_1window
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_set_title
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1set_1title
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_set_bounds
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1set_1bounds
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_navigate
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1navigate
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_init
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1init
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_eval
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1eval
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ca_weblite_webview_WebViewNative
 * Method:    webview_bind
 * Signature: (JLjava/lang/String;Lca/weblite/webview/WebViewNativeCallback;J)V
 */
JNIEXPORT void JNICALL Java_ca_weblite_webview_WebViewNative_webview_1bind
  (JNIEnv *, jclass, jlong, jstring, jobject, jlong);



#ifdef __cplusplus
}
#endif
#endif
